services:
  university_organization:
    build:
      context: ./university_organization
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./university_organization/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://qwey189t:7opsd95sd@shared_db:5432/university_shared_db
    networks:
      - university_network
    depends_on:
      shared_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s



  university_student_test:
    build:
      context: ./university_student_test
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    env_file:
      - ./university_student_test/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://qwey189t:7opsd95sd@shared_db:5432/university_shared_db
    networks:
      - university_network
    depends_on:
      university_organization:
        condition: service_healthy
      shared_db:
        condition: service_healthy



  shared_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=qwey189t
      - POSTGRES_PASSWORD=7opsd95sd
      - POSTGRES_DB=university_shared_db
    volumes:
      - shared_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qwey189t -d university_shared_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - university_network

  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - university_organization
      - university_student_test
    networks:
      - university_network

volumes:
  shared_db_data:


networks:
  university_network:
    driver: bridge
